[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DBOARD_HAS_PSRAM

lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
    h2zero/NimBLE-Arduino @ ^1.4.1
